POST {{host}}/api/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "token": "{{resetToken}}",
  "email": "{{email}}",
  "password": "{{password}}",
  "password_confirmation": "{{password}}"
}
