POST {{host}}/api/home/users/change-password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current-password": "{{password}}",
  "new-password": "{{password}}",
  "new-password_confirmation": "{{password}}"
}
